### ISSUE TITLE
Plugin not runnable under a URL subpath

### ISSUE THREAD

**Issue by jtprobst** [discourse/discourse-math#8]
We have our Discourse forum running under `https://example.com/forum`. The requests to `/forum` are proxied to a different host which is only running Discourse.

The discourse-math plugin requests config.js, toMathML.js, Safe.js, MathMenu.js under `https://example.com/plugins/discourse-math/mathjax/jax/input/TeX/config.js?V=2.7.1`. However, the path `/plugins` is not routed in our proxy, so the requests fail with 404. The correct path to request the files from would be `/forum/plugins`.

I have tried the following changes in the app.yml of Discourse
```
  - replace:
     filename: /var/www/discourse/plugins/discourse-math/assets/javascripts/initializers/discourse-math.js.es6
     from: "root: '/plugins/discourse-math/mathjax'"
     to: "root: '/forum/plugins/discourse-math/mathjax'"
  - replace:
     filename: /var/www/discourse/plugins/discourse-math/assets/javascripts/initializers/discourse-math.js.es6
     from: "return loadScript('/plugins/discourse-math/mathjax/MathJax.1.7.1.js');"
     to: "return loadScript('/forum/plugins/discourse-math/mathjax/MathJax.1.7.1.js');"
```

but it doesn't work, although the changes have been applied correctly. How can the plugin be configured such that it requests those resources under a subpath?
